name: Publish to Zenodo on new release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Download archive
      env:
        tarball: ${{ github.event.release.tarball_url }}
      run: |
        name=$(basename ${tarball})
        curl -L $tarball > $name
        echo "archive=${name}" >> $GITHUB_ENV

    - name: Extract clean title and version
      id: extract
      run: |
        RELEASE_TITLE="${{ github.event.release.name }}"
        VERSION="${{ github.ref_name }}"
        CLEAN_TITLE=$(echo "$RELEASE_TITLE" | sed "s/ $VERSION$//")
        echo "clean_title=$CLEAN_TITLE" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Run Zenodo Deploy
      uses: rseng/zenodo-release@a9c88701a0176df755015f8ca4cf8cc754162f27 # v0.0.21
      with:
        token: ${{ secrets.ZENODO_TOKEN }}
        version: ${{ steps.extract.outputs.version }}
        zenodo_json: .zenodo.json
        archive: ${{ env.archive }}
        doi: '10.5281/zenodo.21742982'
        title: ${{ steps.extract.outputs.clean_title }}
